spring:
  config:
    import:
      - classpath:db.properties
      #- classpath:oauth.properties

  datasource:
    driver: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email

          naver:
            client-id: ${oauth.naver.client-id}
            client-secret: ${oauth.naver.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - profile
              - email
            client-name: naver-client-app

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace